-- KOZLU GSB HUB / migration 001. Yeni Supabase projesinde bir kez çalıştırın.
begin;
revoke create on schema public from public,anon,authenticated;
create extension if not exists pgcrypto;
create extension if not exists btree_gist;
create table public.organizations(id uuid primary key default gen_random_uuid(), district_id text not null default 'kozlu', slug text not null unique check(slug ~ '^[a-z][a-z0-9-]+$'), name text not null, created_at timestamptz not null default now());
create table public.memberships(id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations, user_id uuid not null references auth.users, name text not null check(length(name) between 1 and 100), role text not null check(role in ('director','manager','staff')), active boolean not null default true, created_at timestamptz not null default now(), unique(organization_id,user_id),unique(organization_id,id));
create or replace function public.has_role(org uuid, allowed text[] default array['director','manager','staff']) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from memberships m where m.organization_id=org and m.user_id=auth.uid() and m.active and m.role=any(allowed) and (m.role='staff' or auth.jwt()->>'aal'='aal2')); $$;
create or replace function public.my_member(org uuid) returns uuid language sql stable security definer set search_path=public as $$ select id from memberships where organization_id=org and user_id=auth.uid() and active limit 1 $$;
create table public.facilities(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations,name text not null check(length(name) between 1 and 150),status text not null default 'active' check(status in ('active','maintenance','closed')),capacity int check(capacity>=0),description text not null default '' check(length(description)<=3000),is_public boolean not null default false,created_at timestamptz not null default now(),unique(organization_id,id));
create table public.events(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations,name text not null check(length(name) between 1 and 150),category text not null check(category in ('Spor','Eğitim','Kültür-Sanat','Gönüllülük','Toplantı','Kurum ziyareti')),starts_at timestamptz not null,ends_at timestamptz not null,facility_id uuid not null,responsible_id uuid not null,capacity int not null check(capacity between 1 and 100000),expected_attendance int not null default 0 check(expected_attendance>=0),age_group text not null default 'Tümü',status text not null default 'planned' check(status in ('planned','completed','cancelled')),description text not null default '' check(length(description)<=3000),is_public boolean not null default false,attendance_token uuid not null unique default gen_random_uuid(),created_at timestamptz not null default now(),unique(organization_id,id),foreign key(organization_id,facility_id) references public.facilities(organization_id,id),foreign key(organization_id,responsible_id) references public.memberships(organization_id,id),check(ends_at>starts_at),exclude using gist(organization_id with =,facility_id with =,tstzrange(starts_at,ends_at,'[)') with &&) where(status<>'cancelled'));
create table public.event_statistics(id uuid primary key default gen_random_uuid(),organization_id uuid not null,event_id uuid not null unique,qr_count int not null default 0 check(qr_count>=0),actual_attendance int check(actual_attendance>=0),foreign key(organization_id,event_id) references public.events(organization_id,id) on delete cascade);
create table public.tasks(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations,name text not null check(length(name) between 1 and 150),assigned_to uuid not null,event_id uuid,due_at timestamptz not null,priority text not null default 'normal' check(priority in ('normal','high','urgent')),status text not null default 'open' check(status in ('open','in_progress','done')),description text not null default '' check(length(description)<=3000),completed_at timestamptz,created_at timestamptz not null default now(),unique(organization_id,id),foreign key(organization_id,assigned_to) references public.memberships(organization_id,id),foreign key(organization_id,event_id) references public.events(organization_id,id));
create table public.task_items(id uuid primary key default gen_random_uuid(),organization_id uuid not null,task_id uuid not null,name text not null check(length(name) between 1 and 250),done boolean not null default false,created_at timestamptz not null default now(),foreign key(organization_id,task_id) references public.tasks(organization_id,id) on delete cascade);
create table public.maintenance_tickets(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations,name text not null check(length(name) between 1 and 150),facility_id uuid not null,category text not null,priority text not null default 'normal' check(priority in ('low','normal','urgent')),description text not null check(length(description) between 1 and 3000),photo_path text,status text not null default 'open' check(status in ('open','in_progress','resolved')),created_by uuid not null default auth.uid() references auth.users,closed_by uuid references auth.users,closed_at timestamptz,created_at timestamptz not null default now(),foreign key(organization_id,facility_id) references public.facilities(organization_id,id));
create table public.inventory_items(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations,name text not null check(length(name) between 1 and 150),quantity int not null check(quantity>=0),condition text not null default 'good' check(condition in ('good','damaged','repair')),facility_id uuid,description text not null default '' check(length(description)<=3000),created_at timestamptz not null default now(),unique(organization_id,id),foreign key(organization_id,facility_id) references public.facilities(organization_id,id));
create table public.inventory_movements(id uuid primary key default gen_random_uuid(),organization_id uuid not null,item_id uuid not null,actor_id uuid default auth.uid(),before_data jsonb,after_data jsonb,created_at timestamptz not null default now(),foreign key(organization_id,item_id) references public.inventory_items(organization_id,id));
create table public.requests(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations,name text not null check(length(name) between 1 and 150),description text not null check(length(description) between 1 and 3000),priority text not null default 'normal' check(priority in ('normal','high','urgent')),status text not null default 'pending' check(status in ('pending','reviewing','approved','completed','rejected')),created_by uuid not null default auth.uid() references auth.users,created_at timestamptz not null default now());
create table public.institution_partners(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations,name text not null check(length(name) between 1 and 150),kind text not null,description text not null default '' check(length(description)<=3000),created_at timestamptz not null default now(),unique(organization_id,id));
create table public.collaborations(id uuid primary key default gen_random_uuid(),organization_id uuid not null,partner_id uuid not null,event_id uuid not null,outcome text not null default '' check(length(outcome)<=3000),created_at timestamptz not null default now(),foreign key(organization_id,partner_id) references public.institution_partners(organization_id,id),foreign key(organization_id,event_id) references public.events(organization_id,id),unique(partner_id,event_id));
create table public.announcements(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations,name text not null check(length(name) between 1 and 150),body text not null check(length(body) between 1 and 5000),published boolean not null default false,created_at timestamptz not null default now());
create table public.anonymous_ideas(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations,category text not null,body text not null check(length(body) between 10 and 2000),status text not null default 'new' check(status in ('new','reviewing','accepted','archived')),created_at timestamptz not null default now());
create table public.anonymous_feedback(id uuid primary key default gen_random_uuid(),organization_id uuid not null,event_id uuid not null,rating int not null check(rating between 1 and 5),would_return boolean not null,suggestion text not null default '' check(length(suggestion)<=2000),created_at timestamptz not null default now(),foreign key(organization_id,event_id) references public.events(organization_id,id));
-- Ham IP veya kişi bilgisi tutulmaz. Cihaz anahtarı hash'i 90 günlük imha işine dahildir.
create table public.anonymous_receipts(id uuid primary key default gen_random_uuid(),organization_id uuid not null,scope text not null,device_hash text not null,created_at timestamptz not null default now(),unique(scope,device_hash));
create table public.audit_logs(id uuid primary key default gen_random_uuid(),organization_id uuid not null,actor_id uuid,table_name text not null,record_id uuid not null,action text not null,changed_fields text[] not null default '{}',created_at timestamptz not null default now());
create function public.record_audit() returns trigger language plpgsql security definer set search_path=public as $$ declare v jsonb; changed text[]; begin v=to_jsonb(new); if tg_op='UPDATE' then select array_agg(key) into changed from jsonb_each(v) where value is distinct from to_jsonb(old)->key; end if; insert into audit_logs(organization_id,actor_id,table_name,record_id,action,changed_fields) values(new.organization_id,auth.uid(),tg_table_name,new.id,tg_op,coalesce(changed,'{}')); if tg_table_name='inventory_items' then insert into inventory_movements(organization_id,item_id,actor_id,before_data,after_data) values(new.organization_id,new.id,auth.uid(),case when tg_op='UPDATE' then to_jsonb(old) else null end,v);end if; return new;end $$;
create function public.guard_write() returns trigger language plpgsql set search_path=public as $$ begin
if tg_op='UPDATE' and (new.id<>old.id or new.organization_id<>old.organization_id or new.created_at<>old.created_at) then raise exception 'Kayıt kimliği değiştirilemez';end if;
if tg_table_name='maintenance_tickets' then
 if tg_op='UPDATE' and new.created_by<>old.created_by then raise exception 'Kaydı açan değiştirilemez';end if;
 if new.status='resolved' then if tg_op='INSERT' or old.status<>'resolved' then new.closed_at=now();new.closed_by=auth.uid();else new.closed_at=old.closed_at;new.closed_by=old.closed_by;end if;else new.closed_at=null;new.closed_by=null;end if;
end if;
if tg_table_name='tasks' then if new.status='done' and exists(select 1 from public.task_items where task_id=new.id and not done) then raise exception 'Görevi tamamlamadan önce kontrol listesini tamamlayın';end if; if new.status='done' then if tg_op='INSERT' or old.status<>'done' then new.completed_at=now();else new.completed_at=old.completed_at;end if;else new.completed_at=null;end if;
 if tg_op='UPDATE' and not has_role(new.organization_id,array['director','manager']) and (to_jsonb(new)-array['status','completed_at'])<>(to_jsonb(old)-array['status','completed_at']) then raise exception 'Personel yalnız görev durumunu değiştirebilir';end if;
end if;
if tg_table_name='requests' then if tg_op='UPDATE' and new.created_by<>old.created_by then raise exception 'Kaydı açan değiştirilemez';end if;end if;
return new;end $$;
create function public.init_statistics() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into event_statistics(organization_id,event_id) values(new.organization_id,new.id);return new;end $$;
create trigger event_stats after insert on public.events for each row execute function public.init_statistics();
-- Her tablo varsayılan olarak kapalıdır; sadece açık politikalar erişim verir.
do $$ declare t text; begin foreach t in array array['organizations','memberships','facilities','events','event_statistics','tasks','task_items','maintenance_tickets','inventory_items','inventory_movements','requests','institution_partners','collaborations','announcements','anonymous_ideas','anonymous_feedback','anonymous_receipts','audit_logs'] loop execute format('alter table public.%I enable row level security',t);execute format('revoke all on public.%I from anon, authenticated',t);end loop;
foreach t in array array['facilities','events','tasks','task_items','maintenance_tickets','inventory_items','requests','institution_partners','collaborations','announcements','anonymous_ideas'] loop execute format('grant select,insert,update on public.%I to authenticated',t);execute format('create trigger audit_change after insert or update on public.%I for each row execute function public.record_audit()',t);execute format('create trigger guard_change before insert or update on public.%I for each row execute function public.guard_write()',t);end loop;
foreach t in array array['facilities','inventory_items','institution_partners','collaborations','announcements'] loop execute format('create policy read_member on public.%I for select to authenticated using(public.has_role(organization_id))',t);execute format('create policy write_manager on public.%I for all to authenticated using(public.has_role(organization_id,array[''director'',''manager''])) with check(public.has_role(organization_id,array[''director'',''manager'']))',t);end loop;
foreach t in array array['inventory_movements','audit_logs','anonymous_feedback'] loop execute format('grant select on public.%I to authenticated',t);execute format('create policy read_manager on public.%I for select to authenticated using(public.has_role(organization_id,array[''director'',''manager'']))',t);end loop;end $$;
grant select on public.organizations,public.memberships,public.event_statistics to authenticated;
create policy own_org on public.organizations for select to authenticated using(exists(select 1 from memberships where organization_id=organizations.id and user_id=auth.uid() and active));
create policy member_names on public.memberships for select to authenticated using(user_id=auth.uid() or public.has_role(organization_id));
create policy event_read on public.events for select to authenticated using(has_role(organization_id) and (has_role(organization_id,array['director','manager']) or responsible_id=my_member(organization_id)));
create policy event_insert on public.events for insert to authenticated with check(has_role(organization_id) and (has_role(organization_id,array['director','manager']) or responsible_id=my_member(organization_id)));
create policy event_update on public.events for update to authenticated using(has_role(organization_id) and (has_role(organization_id,array['director','manager']) or responsible_id=my_member(organization_id))) with check(has_role(organization_id) and (has_role(organization_id,array['director','manager']) or responsible_id=my_member(organization_id)));
create policy stats_read on public.event_statistics for select to authenticated using(has_role(organization_id));
create policy task_read on public.tasks for select to authenticated using(has_role(organization_id) and (has_role(organization_id,array['director','manager']) or assigned_to=my_member(organization_id)));
create policy task_insert on public.tasks for insert to authenticated with check(has_role(organization_id,array['director','manager']));
create policy task_update on public.tasks for update to authenticated using(has_role(organization_id) and (has_role(organization_id,array['director','manager']) or assigned_to=my_member(organization_id))) with check(has_role(organization_id) and (has_role(organization_id,array['director','manager']) or assigned_to=my_member(organization_id)));
create policy task_item_read on public.task_items for select to authenticated using(exists(select 1 from tasks where id=task_id));
create policy task_item_write on public.task_items for all to authenticated using(has_role(organization_id,array['director','manager'])) with check(has_role(organization_id,array['director','manager']));
create policy issue_read on public.maintenance_tickets for select to authenticated using(has_role(organization_id) and (has_role(organization_id,array['director','manager']) or created_by=auth.uid()));
create policy issue_insert on public.maintenance_tickets for insert to authenticated with check(has_role(organization_id) and created_by=auth.uid() and status='open');
create policy issue_update on public.maintenance_tickets for update to authenticated using(has_role(organization_id,array['director','manager'])) with check(has_role(organization_id,array['director','manager']));
create policy request_read on public.requests for select to authenticated using(has_role(organization_id) and (created_by=auth.uid() or has_role(organization_id,array['director','manager'])));
create policy request_insert on public.requests for insert to authenticated with check(has_role(organization_id) and created_by=auth.uid() and status='pending');
create policy request_update on public.requests for update to authenticated using(has_role(organization_id,array['director','manager'])) with check(has_role(organization_id,array['director','manager']));
create policy idea_read on public.anonymous_ideas for select to authenticated using(has_role(organization_id,array['director','manager']));
create policy idea_update on public.anonymous_ideas for update to authenticated using(has_role(organization_id,array['director','manager'])) with check(has_role(organization_id,array['director','manager']));
create function public.set_attendance(p_event uuid,p_count int) returns void language plpgsql security definer set search_path=public as $$ declare e events;begin select * into e from events where id=p_event; if not found or not has_role(e.organization_id) or not (has_role(e.organization_id,array['director','manager']) or e.responsible_id=my_member(e.organization_id)) then raise exception 'Yetki yok';end if;if p_count<0 or p_count>100000 then raise exception 'Geçersiz katılım';end if;update event_statistics set actual_attendance=p_count where event_id=p_event;insert into audit_logs(organization_id,actor_id,table_name,record_id,action,changed_fields) values(e.organization_id,auth.uid(),'event_statistics',p_event,'UPDATE',array['actual_attendance']);end $$;
create function public.toggle_task_item(p_item uuid,p_done boolean) returns void language plpgsql security definer set search_path=public as $$ declare t tasks;begin select tasks.* into t from tasks join task_items i on i.task_id=tasks.id where i.id=p_item;if not found or not has_role(t.organization_id) or not(has_role(t.organization_id,array['director','manager']) or t.assigned_to=my_member(t.organization_id)) then raise exception 'Yetki yok';end if;update task_items set done=p_done where id=p_item;if not p_done and t.status='done' then update tasks set status='in_progress' where id=t.id;end if;end $$;
create function public.save_task(p_data jsonb,p_items text[]) returns uuid language plpgsql security definer set search_path=public as $$ declare v uuid;org uuid:=(p_data->>'organization_id')::uuid;begin if not has_role(org,array['director','manager']) then raise exception 'Yetki yok';end if; if cardinality(p_items)>50 then raise exception 'En fazla 50 kontrol maddesi';end if;if cardinality(p_items)>0 and p_data->>'status'='done' then raise exception 'Kontrol listeli yeni görevi önce açık oluşturun';end if;insert into tasks(organization_id,name,assigned_to,event_id,due_at,priority,status,description) values(org,p_data->>'name',(p_data->>'assigned_to')::uuid,nullif(p_data->>'event_id','')::uuid,(p_data->>'due_at')::timestamptz,p_data->>'priority',p_data->>'status',coalesce(p_data->>'description','')) returning id into v;insert into task_items(organization_id,task_id,name) select org,v,trim(x) from unnest(p_items) x where trim(x)<>'';return v;end $$;
create function public.public_program(p_slug text) returns jsonb language sql stable security definer set search_path=public as $$ select jsonb_build_object('organization',jsonb_build_object('id',o.id,'name',o.name),'events',coalesce((select jsonb_agg(jsonb_build_object('id',e.id,'name',e.name,'category',e.category,'starts_at',e.starts_at,'ends_at',e.ends_at,'facility_id',e.facility_id,'capacity',e.capacity,'description',e.description,'age_group',e.age_group) order by e.starts_at) from events e where e.organization_id=o.id and e.is_public and e.status<>'cancelled' and e.ends_at>now()-interval '1 day' and e.starts_at<now()+interval '90 days'),'[]'::jsonb),'facilities',coalesce((select jsonb_agg(jsonb_build_object('id',f.id,'name',f.name,'status',f.status,'description',f.description)) from facilities f where f.organization_id=o.id and f.is_public),'[]'::jsonb),'announcements',coalesce((select jsonb_agg(jsonb_build_object('id',a.id,'name',a.name,'body',a.body,'created_at',a.created_at) order by a.created_at desc) from announcements a where a.organization_id=o.id and a.published),'[]'::jsonb)) from organizations o where o.slug=p_slug $$;
create function public.public_event(p_token uuid) returns jsonb language sql stable security definer set search_path=public as $$ select jsonb_build_object('id',id,'name',name,'starts_at',starts_at,'ends_at',ends_at,'status',status,'attendance_open',now() between starts_at-interval '1 hour' and ends_at+interval '2 hours','feedback_open',now() between starts_at and ends_at+interval '7 days') from events where attendance_token=p_token and is_public and status<>'cancelled' $$;
-- Anonim uçlar, ham tablolara erişim açmadan sınırlı yazma yapar.
create function public.anonymous_submit(p_kind text,p_slug text,p_token uuid,p_device uuid,p_data jsonb) returns jsonb language plpgsql security definer set search_path=public as $$ declare org uuid;e events;v_scope text;v_hash text;begin
if p_device is null then raise exception 'Cihaz anahtarı eksik';end if;
if p_kind='idea' then select id into org from organizations where slug=p_slug;v_scope='idea:'||org||':'||date_trunc('hour',now())::text;
else select * into e from events where attendance_token=p_token and is_public and status<>'cancelled';org=e.organization_id;v_scope=p_kind||':'||e.id;end if;
if org is null then raise exception 'Kayıt bulunamadı';end if;
perform pg_advisory_xact_lock(hashtextextended(org::text,0));
if (select count(*) from anonymous_receipts where organization_id=org and created_at>now()-interval '1 hour')>=1000 then raise exception 'Yoğunluk nedeniyle daha sonra tekrar deneyin';end if;
v_hash=encode(sha256(convert_to(p_device::text||v_scope,'UTF8')),'hex');
if exists(select 1 from anonymous_receipts where scope=v_scope and device_hash=v_hash) then return jsonb_build_object('duplicate',true);end if;
if p_kind='attendance' then
 if now()<e.starts_at-interval '1 hour' or now()>e.ends_at+interval '2 hours' then raise exception 'Katılım sayımı şu an kapalı';end if;
 update event_statistics set qr_count=qr_count+1 where event_id=e.id;
elsif p_kind='feedback' then
 if now()<e.starts_at or now()>e.ends_at+interval '7 days' then raise exception 'Değerlendirme süresi kapalı';end if;
 insert into anonymous_feedback(organization_id,event_id,rating,would_return,suggestion) values(org,e.id,(p_data->>'rating')::int,(p_data->>'would_return')::boolean,coalesce(p_data->>'suggestion',''));
elsif p_kind='idea' then
 if not(p_data->>'category'=any(array['Spor','Teknoloji','Kültür','Sanat','Eğitim','Gönüllülük','Diğer'])) then raise exception 'Geçersiz kategori';end if;
 insert into anonymous_ideas(organization_id,category,body) values(org,p_data->>'category',p_data->>'body');
else raise exception 'Geçersiz işlem';end if;
insert into anonymous_receipts(organization_id,scope,device_hash) values(org,v_scope,v_hash);return jsonb_build_object('saved',true);end $$;
create function public.manage_member(p_org uuid,p_email text,p_name text,p_role text,p_active boolean default true) returns void language plpgsql security definer set search_path=public as $$ declare u uuid;begin if not has_role(p_org,array['director']) then raise exception 'Müdür yetkisi gerekli';end if;select id into u from auth.users where lower(email)=lower(trim(p_email));if u is null then raise exception 'Önce Supabase Auth üzerinden personeli davet edin';end if;if u=auth.uid() then raise exception 'Kendi yetkinizi bu ekrandan değiştiremezsiniz';end if;insert into memberships(organization_id,user_id,name,role,active) values(p_org,u,p_name,p_role,p_active) on conflict(organization_id,user_id) do update set name=excluded.name,role=excluded.role,active=excluded.active;insert into audit_logs(organization_id,actor_id,table_name,record_id,action) values(p_org,auth.uid(),'memberships',u,'UPSERT');end $$;
-- EXECUTE varsayılanı PUBLIC olmasın. Trigger işlevleri doğrudan çağrılmaz.
revoke execute on all functions in schema public from public,anon,authenticated;
grant execute on function public.has_role(uuid,text[]),public.my_member(uuid),public.set_attendance(uuid,int),public.toggle_task_item(uuid,boolean),public.save_task(jsonb,text[]),public.manage_member(uuid,text,text,text,boolean) to authenticated;
grant execute on function public.public_program(text),public.public_event(uuid),public.anonymous_submit(text,text,uuid,uuid,jsonb) to anon,authenticated;
create index events_org_start on public.events(organization_id,starts_at);
create index tasks_org_due on public.tasks(organization_id,due_at);
create index issues_org_state on public.maintenance_tickets(organization_id,status);
create index receipts_time on public.anonymous_receipts(organization_id,created_at);
create index audit_org_date on public.audit_logs(organization_id,created_at desc);
commit;

