begin;
create function public.monthly_report(p_org uuid,p_month date) returns jsonb language plpgsql stable security definer set search_path=public as $$ declare a timestamptz;b timestamptz;r jsonb;begin
if not has_role(p_org,array['director','manager']) then raise exception 'Yetki yok';end if;
a=date_trunc('month',p_month::timestamp) at time zone 'Europe/Istanbul';b=(date_trunc('month',p_month::timestamp)+interval '1 month') at time zone 'Europe/Istanbul';
with ev as(select e.*,coalesce(s.actual_attendance,s.qr_count,0) attendance from events e left join event_statistics s on s.event_id=e.id where e.organization_id=p_org and e.starts_at>=a and e.starts_at<b and e.status='completed'),tk as(select * from tasks where organization_id=p_org and created_at>=a and created_at<b),mt as(select * from maintenance_tickets where organization_id=p_org and created_at>=a and created_at<b)
select jsonb_build_object('month',to_char(a at time zone 'Europe/Istanbul','YYYY-MM'),'events',(select count(*) from ev),'attendance',(select coalesce(sum(attendance),0) from ev),'average_attendance',(select coalesce(round(avg(attendance),1),0) from ev),'facility_hours',(select coalesce(round(sum(extract(epoch from (ends_at-starts_at))/3600),1),0) from ev),'volunteering',(select count(*) from ev where category='Gönüllülük'),'collaborations',(select count(distinct c.event_id) from collaborations c join ev on ev.id=c.event_id),'tasks_opened',(select count(*) from tk),'tasks_completed',(select count(*) from tk where status='done'),'issues_opened',(select count(*) from mt),'issues_resolved',(select count(*) from mt where status='resolved'),'resolution_days',(select round(avg(extract(epoch from (closed_at-created_at))/86400),1) from mt where status='resolved'),'satisfaction',(select round(avg(f.rating),1) from anonymous_feedback f join ev on ev.id=f.event_id),'feedback_count',(select count(*) from anonymous_feedback f join ev on ev.id=f.event_id),'categories',coalesce((select jsonb_agg(x) from(select category,count(*) events,sum(attendance) attendance from ev group by category order by sum(attendance) desc)x),'[]'::jsonb),'age_groups',coalesce((select jsonb_agg(x) from(select age_group,sum(attendance) attendance from ev group by age_group)x),'[]'::jsonb),'attendance_source','Personel onaylı sayı varsa o kullanılır; yoksa anonim QR sayımı. Tekil kişi sayısı değildir.') into r;return r;end $$;
create function public.dashboard(p_org uuid) returns jsonb language plpgsql stable security definer set search_path=public as $$ declare r jsonb;begin if not has_role(p_org) then raise exception 'Yetki yok veya iki adımlı doğrulama gerekli';end if;
with ev as(select e.*,coalesce(s.actual_attendance,s.qr_count,0) attendance from events e left join event_statistics s on s.event_id=e.id where e.organization_id=p_org and (has_role(p_org,array['director','manager']) or e.responsible_id=my_member(p_org)) and e.status<>'cancelled' and (e.starts_at at time zone 'Europe/Istanbul')::date=(now() at time zone 'Europe/Istanbul')::date)
select jsonb_build_object('events',(select count(*) from ev),'attendance',(select coalesce(sum(attendance),0) from ev),'facilities',(select count(distinct facility_id) from ev),'staff',(select count(distinct responsible_id) from ev),'tasks',(select count(*) from tasks where organization_id=p_org and status<>'done' and (has_role(p_org,array['director','manager']) or assigned_to=my_member(p_org))),'issues',(select count(*) from maintenance_tickets where organization_id=p_org and status<>'resolved' and (has_role(p_org,array['director','manager']) or created_by=auth.uid())),'program',coalesce((select jsonb_agg(to_jsonb(ev) order by starts_at) from ev),'[]'::jsonb)) into r;return r;end $$;
create function public.insights(p_org uuid) returns jsonb language plpgsql stable security definer set search_path=public as $$ begin if not has_role(p_org,array['director','manager']) then raise exception 'Yetki yok';end if;return jsonb_build_object(
'capacity',coalesce((select jsonb_agg(x) from(select e.category,count(*) events,round(100.0*sum(coalesce(s.actual_attendance,s.qr_count,0))/nullif(sum(e.capacity),0),1) occupancy from events e join event_statistics s on s.event_id=e.id where e.organization_id=p_org and e.status='completed' and e.starts_at>now()-interval '28 days' and e.starts_at<=now() group by e.category)x),'[]'::jsonb),
'ideas',coalesce((select jsonb_agg(x) from(select category,count(*) filter(where created_at>now()-interval '30 days') recent,count(*) filter(where created_at<=now()-interval '30 days') previous from anonymous_ideas where organization_id=p_org and created_at>now()-interval '60 days' group by category order by count(*) desc)x),'[]'::jsonb),
'busy_times',coalesce((select jsonb_agg(x) from(select extract(isodow from starts_at at time zone 'Europe/Istanbul') as day_number,extract(hour from starts_at at time zone 'Europe/Istanbul') as hour_number,count(*) events from events where organization_id=p_org and status='completed' and starts_at between now()-interval '30 days' and now() group by 1,2 order by count(*) desc limit 5)x),'[]'::jsonb),
'satisfaction',(select round(avg(rating),1) from anonymous_feedback where organization_id=p_org and created_at>now()-interval '30 days'));
end $$;
revoke all on function public.monthly_report(uuid,date),public.dashboard(uuid),public.insights(uuid) from public;
grant execute on function public.monthly_report(uuid,date),public.dashboard(uuid),public.insights(uuid) to authenticated;
-- Özel fotoğraflar: herkese açık URL yok, kurum yetkisi ve kısa süreli signed URL.
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('issue-photos','issue-photos',false,5242880,array['image/jpeg','image/png','image/webp']) on conflict(id) do nothing;
create policy issue_photo_read on storage.objects for select to authenticated using(bucket_id='issue-photos' and public.has_role(((storage.foldername(name))[1])::uuid));
create policy issue_photo_insert on storage.objects for insert to authenticated with check(bucket_id='issue-photos' and public.has_role(((storage.foldername(name))[1])::uuid) and (storage.foldername(name))[2]=auth.uid()::text);
create policy issue_photo_delete on storage.objects for delete to authenticated using(bucket_id='issue-photos' and owner_id=auth.uid()::text);
commit;


